version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: pgpassword
  pgadmin:
    image: dpage/pgadmin4:4.12
    ports:
      - 127.0.0.1:2082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
  tsplay:
    image: node:10-alpine
    ports:
      - 127.0.0.1:2080:2080
      - 127.0.0.1:2090:2090
    volumes:
      - ../frontend/dist:/frontend
      - ../dist:/server
    environment:
      STORAGE_TYPE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: tsplayuser
      POSTGRES_PASSWORD: tsplaypassword
      FRONTEND_PATH: /frontend
    command:
      - node
      - /server/server/src/dev-reload.js
      - /server/server/src/server.js
