version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: pgpassword
  phppgadmin:
    image: dockage/phppgadmin:latest
    ports:
      - 127.0.0.1:2081:80
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
  tsplay:
    image: node:10-alpine
    ports:
      - 127.0.0.1:2080:2080
    volumes:
      - ../frontend/dist:/frontend
      - ../dist:/server
    environment:
      STORAGE_TYPE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: tsplayuser
      POSTGRES_PASSWORD: tsplaypassword
      FRONTEND_PATH: /frontend
    command:
      - node
      - /server/server/src/server
